defmodule PromptOnSDK.ConformanceTest do
  @moduledoc """
  Executes `conformance/*.json` against this SDK.

  Those files are the cross-language contract: every other PromptOn SDK ships them in its own test
  suite and must produce the same results. They are generated by `mix run
  scripts/gen_conformance.exs`, so this test is what keeps them honest — if the SDK changes
  behaviour and the fixtures are not regenerated, this fails.
  """

  use ExUnit.Case, async: true

  alias PromptOnSDK.{Payload, Resolver, StopKind, Template, UseCaseDocument}

  @dir Path.expand("../../conformance", __DIR__)
  @files ~w(template.json use_case.json truncation.json stop_kind.json log_record.json)

  @payload_config %{
    payload_defaults: %{mode: :full, sample_rate: 1.0, max_bytes: 262_144},
    hash_end_user: false,
    log: %{}
  }

  @required_record_fields ~w(id use_case model status started_at)
  @error_kinds ~w(http_4xx http_5xx rate_limited timeout transport parse app)
  @stop_kinds ~w(stop length tool_call content_filter other)
  @kinds ~w(chat text embedding)
  @providers ~w(openrouter groq openai anthropic google other)
  @sources ~w(remote disk bundle manual)
  @cost_sources ~w(provider catalog unknown)
  @uuid ~r/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/

  # ---------------------------------------------------------------------------
  # template.json

  test "template.json: every render case matches" do
    for c <- load("template.json")["cases"] do
      engine = String.to_existing_atom(c["engine"])
      actual = render_expectation(Template.render(c["template"], c["variables"], engine: engine))
      assert actual == c["expect"], "template case #{c["name"]}"
    end
  end

  test "template.json: every lint case matches" do
    for c <- load("template.json")["lint_cases"] do
      assert lint_expectation(Template.lint(c["template"])) == c["expect"],
             "lint case #{c["name"]}"
    end
  end

  test "template.json: every detected-variables case matches" do
    for c <- load("template.json")["variables_cases"] do
      assert %{"variables" => Template.variables(c["template"])} == c["expect"],
             "variables case #{c["name"]}"
    end
  end

  test "template.json: the declared whitelists are the SDK's" do
    doc = load("template.json")
    assert doc["allowed_tags"] == Template.allowed_tags()
    assert doc["allowed_filters"] == Template.allowed_filters()
  end

  # ---------------------------------------------------------------------------
  # use_case.json

  test "use_case.json: every use-case document decodes as schema v4" do
    for {ref, raw} <- load("use_case.json")["documents"] do
      assert {:ok, data, _warnings} = UseCaseDocument.decode(raw), "document #{ref}"
      assert data.schema_version == UseCaseDocument.schema_version()
    end
  end

  test "use_case.json: every use-case case matches" do
    doc = load("use_case.json")
    assert doc["default_prompt"] == Resolver.default_prompt()

    documents =
      Map.new(doc["documents"], fn {ref, raw} ->
        {:ok, data, _} = UseCaseDocument.decode(raw)
        {ref, data}
      end)

    for c <- doc["cases"] do
      data = Map.fetch!(documents, c["document_ref"])
      assert data.environment == c["environment"], "environment of #{c["name"]}"

      actual = use_case_expectation(data, c["use_case"], c["prompt"], c["variables"])
      assert actual == c["expect"], "use case #{c["name"]}"
    end
  end

  # ---------------------------------------------------------------------------
  # truncation.json

  test "truncation.json: every payload-policy case matches" do
    for c <- load("truncation.json")["cases"] do
      policy = %{
        mode: String.to_existing_atom(c["policy"]["mode"]),
        sample_rate: c["policy"]["sample_rate"],
        max_bytes: c["policy"]["max_bytes"]
      }

      config = %{@payload_config | hash_end_user: get_in(c, ["config", "hash_end_user"]) == true}

      assert Payload.apply(c["log"], policy, config) == c["expect"]["log"],
             "truncation case #{c["name"]}"
    end
  end

  test "truncation.json: the sampling buckets match" do
    for %{"id" => id, "bucket" => bucket} <- load("truncation.json")["sampling"]["buckets"] do
      assert Payload.bucket(id) == bucket, "bucket of #{inspect(id)}"
    end
  end

  test "truncation.json: every truncated string stays valid UTF-8 and within its cap" do
    for c <- load("truncation.json")["cases"] do
      max_bytes = c["policy"]["max_bytes"]
      gen = c["expect"]["log"]

      for message <- get_in(gen, ["input", "messages"]) || [],
          is_binary(message["content"]) do
        assert String.valid?(message["content"]), "#{c["name"]}: message content must be UTF-8"

        assert byte_size(message["content"]) <= max(div(max_bytes, 8), 64),
               "#{c["name"]}: message content over the per-message cap"
      end

      if content = get_in(gen, ["output", "content"]) do
        assert String.valid?(content), "#{c["name"]}: output content must be UTF-8"
        assert byte_size(content) <= max(div(max_bytes, 4), 64), "#{c["name"]}: output over cap"
      end
    end
  end

  # ---------------------------------------------------------------------------
  # stop_kind.json

  test "stop_kind.json: every finish_reason maps to the documented stop_kind" do
    for c <- load("stop_kind.json")["cases"] do
      kind = StopKind.normalize(c["finish_reason"])
      assert to_string(kind) == c["stop_kind"], "stop_kind of #{inspect(c["finish_reason"])}"

      assert StopKind.truncated?(kind) == c["truncated"],
             "truncated? of #{inspect(c["finish_reason"])}"

      assert StopKind.normalize(to_string(kind)) == kind, "normalization must be idempotent"
    end
  end

  # ---------------------------------------------------------------------------
  # log_record.json

  test "log_record.json: every record satisfies the server's ingest rules" do
    for %{"name" => name, "record" => r} <- load("log_record.json")["records"] do
      for key <- @required_record_fields do
        assert Map.has_key?(r, key), "#{name} is missing the required field #{key}"
      end

      assert r["id"] =~ @uuid, "#{name}: id must be a UUID"
      assert String.at(r["id"], 14) == "7", "#{name}: id must be a UUIDv7, not a v4"
      assert r["status"] in ~w(ok error), "#{name}: status"
      assert {:ok, _dt, _offset} = DateTime.from_iso8601(r["started_at"]), "#{name}: started_at"
      assert byte_size(r["use_case"]) <= 512, "#{name}: use_case"
      assert byte_size(r["model"]) <= 512, "#{name}: model"

      assert_optional_enum(r["kind"], @kinds, "#{name}: kind")
      assert_optional_enum(r["provider"], @providers, "#{name}: provider")
      assert_optional_enum(r["stop_kind"], @stop_kinds, "#{name}: stop_kind")
      assert_optional_enum(r["source"], @sources, "#{name}: source")

      assert_optional_enum(
        get_in(r, ["usage", "cost_source"]),
        @cost_sources,
        "#{name}: cost_source"
      )

      for key <- ~w(deployment_id prompt_version_id model_id), not is_nil(r[key]) do
        assert r[key] =~ @uuid, "#{name}: #{key} must be a UUID"
      end

      if error = r["error"] do
        assert error["kind"] in @error_kinds, "#{name}: error.kind"
        assert byte_size(error["message"] || "") <= 2_048, "#{name}: error.message"
      end

      assert byte_size(Jason.encode!(r["context"] || %{})) <= 2_048, "#{name}: context"
      assert byte_size(Jason.encode!(r["metadata"] || %{})) <= 4_096, "#{name}: metadata"
      assert byte_size(Jason.encode!(r["params"] || %{})) <= 4_096, "#{name}: params"

      assert byte_size(Jason.encode!(get_in(r, ["usage", "raw"]) || %{})) <= 16_384,
             "#{name}: usage.raw"

      json = Jason.encode!(r)
      assert String.valid?(json), "#{name}: must be valid UTF-8"
      assert :binary.match(json, <<0>>) == :nomatch, "#{name}: must contain no NUL byte"
    end
  end

  test "log_record.json: every record already satisfies the default payload caps" do
    for %{"name" => name, "record" => r} <- load("log_record.json")["records"] do
      policy = %{mode: :full, sample_rate: 1.0, max_bytes: 262_144}

      assert Payload.apply(r, policy, @payload_config) == r,
             "#{name} should pass through the payload policy unchanged"
    end
  end

  test "log_record.json: the batch envelope holds exactly the documented records" do
    doc = load("log_record.json")
    records = Enum.map(doc["records"], & &1["record"])

    assert doc["batch_envelope"]["request"]["logs"] == records
    assert doc["batch_envelope"]["response_example"]["accepted"] == length(records)
    assert doc["batch_envelope"]["response_on_resend"]["duplicates"] == length(records)
    assert length(records) <= doc["endpoint"]["max_records_per_request"]
  end

  # ---------------------------------------------------------------------------

  test "every fixture records the SDK version it was generated from" do
    for name <- @files do
      doc = load(name)
      assert doc["generated_from"]["sdk_version"] == PromptOnSDK.version(), name
      assert doc["format_version"] == 1, name
      assert doc["conformance"] == Path.rootname(name), name
    end
  end

  # ---------------------------------------------------------------------------
  # helpers

  defp load(name), do: @dir |> Path.join(name) |> File.read!() |> Jason.decode!()

  defp render_expectation({:ok, output}), do: %{"output" => output}

  defp render_expectation({:error, {:missing_variable, name}}),
    do: %{"error" => "missing_variable", "variable" => name}

  defp render_expectation({:error, {:parse, _}}), do: %{"error" => "parse_error"}
  defp render_expectation({:error, {:render, _}}), do: %{"error" => "render_error"}

  defp lint_expectation(:ok), do: %{"lint" => "ok"}

  defp lint_expectation({:error, reasons}) do
    %{
      "lint" => "error",
      "reasons" =>
        Enum.map(reasons, fn {kind, value} ->
          %{"kind" => to_string(kind), "value" => to_string(value)}
        end)
    }
  end

  defp use_case_expectation(data, use_case, prompt, variables) do
    case Resolver.resolve(data, use_case, prompt: prompt) do
      {:error, :unknown_prompt} ->
        {:ok, prompts} = Resolver.prompt_names(data, use_case)

        %{
          "error" => "unknown_prompt",
          "prompt" => prompt || Resolver.default_prompt(),
          "prompt_names" => prompts
        }

      {:error, reason} ->
        %{"error" => to_string(reason)}

      {:ok, r} ->
        case fill_use_case(r, variables) do
          {:error, {:missing_variable, name}} ->
            %{"error" => "missing_variable", "variable" => name}

          {:ok, rendered} ->
            {:ok, prompts} = Resolver.prompt_names(data, use_case)

            %{
              "kind" => to_string(r.kind),
              "deployment_id" => r.deployment_id,
              "revision" => r.deployment_revision,
              "prompt" => r.prompt,
              "prompt_names" => prompts,
              "model_id" => r.model_id,
              "model" => r.model,
              "provider" => r.provider && to_string(r.provider),
              "params" => r.params,
              "provider_options" => r.provider_options,
              "prompt_version" =>
                r.prompt_version_id &&
                  %{"id" => r.prompt_version_id, "number" => r.prompt_version_number},
              "warnings" => Enum.map(r.warnings, fn {tag, detail} -> "#{tag}: #{detail}" end)
            }
            |> Map.merge(rendered)
        end
    end
  end

  defp fill_use_case(%{kind: :chat, messages: messages}, nil) when is_list(messages),
    do: {:ok, %{"messages" => Enum.map(messages, &message_map/1)}}

  defp fill_use_case(%{kind: :chat, messages: messages} = r, variables)
       when is_list(messages) do
    case Template.render_messages(messages, variables, engine: r.engine || :liquid) do
      {:ok, rendered} -> {:ok, %{"messages" => Enum.map(rendered, &message_map/1)}}
      error -> error
    end
  end

  defp fill_use_case(%{kind: :text, text_template: text}, nil) when is_binary(text),
    do: {:ok, %{"text" => text}}

  defp fill_use_case(%{kind: :text, text_template: text} = r, variables)
       when is_binary(text) do
    case Template.render(text, variables, engine: r.engine || :liquid) do
      {:ok, rendered} -> {:ok, %{"text" => rendered}}
      error -> error
    end
  end

  defp fill_use_case(_r, _variables), do: {:ok, %{}}

  defp message_map(m), do: %{"role" => m[:role], "content" => m[:content]}

  defp assert_optional_enum(nil, _allowed, _label), do: :ok

  defp assert_optional_enum(value, allowed, label),
    do: assert(value in allowed, "#{label} = #{inspect(value)}")
end
